# -*- coding: utf-8 -*-
"""swieta4zajecia0812.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6p5g4S54w7qyU4A-MlsI4vqWELVKHxM
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

# --- Konfiguracja i stałe ---

# Kolory
KOLOR_CZAPKA_DOMYSLNY = 'red'
KOLOR_CZAPKA_ZMIANA = 'blue'
KOLOR_BRODA = '#f5f5dc'
KOLOR_TWARZ = '#ffe0bd'
KOLOR_OCZY = 'black'
KOLOR_POMPON_FUTERKO = 'white'

# Nazwa zmiennej stanu do przechowywania koloru czapki
STAN_KOLOR_CZAPKI = 'kolor_czapki'


def stworz_mikolaja(kolor_czapki):
    """
    Tworzy i zwraca obiekt Matplotlib Figure (Mikołaja).
    """
    fig, ax = plt.subplots(figsize=(6, 8))
    ax.set_aspect('equal', adjustable='box')
    ax.set_xlim(-1, 1)
    ax.set_ylim(-1, 1.2)
    ax.axis('off')  # Ukryj osie

    # --- Rysowanie Mikołaja (jak w oryginalnym kodzie) ---

    # Twarz (koło)
    twarz = patches.Circle((0, 0), 0.4, facecolor=KOLOR_TWARZ)
    ax.add_patch(twarz)

    # Broda
    broda = patches.Circle((0, -0.1), 0.5, facecolor=KOLOR_BRODA)
    ax.add_patch(broda)

    # Wąsy
    wasy_lewy = patches.Rectangle((-0.3, -0.1), 0.15, 0.05, angle=10, color=KOLOR_POMPON_FUTERKO)
    wasy_prawy = patches.Rectangle((0.15, -0.1), 0.15, 0.05, angle=-10, color=KOLOR_POMPON_FUTERKO)
    ax.add_patch(wasy_lewy)
    ax.add_patch(wasy_prawy)

    # Oczy
    oko_lewe = patches.Circle((-0.15, 0.15), 0.05, facecolor=KOLOR_OCZY)
    oko_prawe = patches.Circle((0.15, 0.15), 0.05, facecolor=KOLOR_OCZY)
    ax.add_patch(oko_lewe)
    ax.add_patch(oko_prawe)

    # Czapka (trójkąt) - Używamy przekazanego koloru
    czapka_wierzcholki = np.array([
        [-0.45, 0.3],
        [0.45, 0.3],
        [0, 1.0]
    ])
    czapka_patch = patches.Polygon(czapka_wierzcholki, closed=True, facecolor=kolor_czapki, zorder=5)
    ax.add_patch(czapka_patch)

    # Futerko/Obręcz czapki
    futerko = patches.Rectangle((-0.5, 0.25), 1.0, 0.1, facecolor=KOLOR_POMPON_FUTERKO, zorder=6)
    ax.add_patch(futerko)

    # Pompon
    pompon = patches.Circle((0, 1.0), 0.1, facecolor=KOLOR_POMPON_FUTERKO, zorder=7)
    ax.add_patch(pompon)

    plt.title("Wesołych Świąt! Kolor czapki: {}".format(kolor_czapki.upper()))

    return fig


def zmien_kolor():
    """
    Funkcja zmieniająca kolor czapki w stanie Streamlit.
    """
    obecny_kolor = st.session_state[STAN_KOLOR_CZAPKI]
    if obecny_kolor == KOLOR_CZAPKA_DOMYSLNY:
        nowy_kolor = KOLOR_CZAPKA_ZMIANA
    else:
        nowy_kolor = KOLOR_CZAPKA_DOMYSLNY

    st.session_state[STAN_KOLOR_CZAPKI] = nowy_kolor


def main():
    st.set_page_config(page_title="Interaktywny Mikołaj", layout="centered")
    st.title("Interaktywny Mikołaj w Streamlit 🧑‍🎄")
    st.markdown("Kliknij przycisk, aby zmienić kolor czapki!")

    # 1. Inicjalizacja stanu (Session State)
    # Streamlit musi pamiętać stan między przeładowaniami
    if STAN_KOLOR_CZAPKI not in st.session_state:
        st.session_state[STAN_KOLOR_CZAPKI] = KOLOR_CZAPKA_DOMYSLNY

    # 2. Przycisk
    # Kliknięcie przycisku wywołuje funkcję zmien_kolor, która modyfikuje stan,
    # co z kolei powoduje ponowne uruchomienie skryptu (i odświeżenie Mikołaja).
    st.button(
        "Zmień Kolor Czapki!",
        on_click=zmien_kolor
    )

    st.write("---")

    # 3. Rysowanie Mikołaja
    # Pobierz aktualny kolor ze stanu
    aktualny_kolor = st.session_state[STAN_KOLOR_CZAPKI]

    # Stwórz figurę Matplotlib z aktualnym kolorem
    mikolaj_fig = stworz_mikolaja(aktualny_kolor)

    # Wyświetl figurę w Streamlit
    st.pyplot(mikolaj_fig)


if __name__ == '__main__':
    main()